name: 'ncd_insurance_analytics'
version: '1.0.0'
config-version: 2

profile: 'ncd_insurance_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ncd_insurance_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

seeds:
  ncd_insurance_analytics:
    +schema: raw

vars:
  start_date: '2023-01-01'
  end_date: '2024-12-31'
